[profile.default]
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = false
evm_version = "london"
src = "src"
out = "out"
libs = ["lib"]

[fmt]
line_length = 100
multiline_func_header = "params_first"
# wrap_comments = true


[profile.production]
via_ir = true

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
