[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_multi_endpoint = "J61k8wq3PMLWmpR8meNxuQWfjHdzf8W1TZrFHoock9ou"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "keys/test.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


[test.validator]
url = "https://api.mainnet-beta.solana.com"
### At 160 ticks/s, 64 ticks per slot implies that leader rotation and voting will happen
### every 400 ms. A fast voting cadence ensures faster finality and convergence
ticks_per_slot = 16

### Wormhole Core Bridge (Mainnet) -- Program
[[test.genesis]]
address = "worm2ZoG2kUd4vFXhvjh93UUH596ayRfgQ2MgjNMTth"
program = "programs/example-native-token-transfers/tests/fixtures/mainnet_core_bridge.so"

### Wormhole Core Bridge (Mainnet) -- Config
[[test.validator.account]]
address = "2yVjuQwpsvdsrywzsJJVs9Ueh4zayyo5DYJbBNc3DDpn"
filename = "tests/accounts/mainnet/core_bridge_config.json"

### Wormhole Core Bridge (Mainnet) -- Fee Collector
[[test.validator.account]]
address = "9bFNrXNb2WTx8fMHXCheaZqkLZ3YCCaiqTftHxeintHy"
filename = "tests/accounts/mainnet/core_bridge_fee_collector.json"

### Wormhole Core Bridge (Mainnet) -- Guardian set 0 (overridden with devnet private key)
[[test.validator.account]]
address = "DS7qfSAgYsonPpKoAjcGhX9VFjXdGkiHjEDkTidf8H2P"
filename = "tests/accounts/mainnet/guardian_set_0.json"
