[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.10"

[features]
seeds = false
skip-lint = false

[programs.localnet]
example_native_token_transfers = "NttF2XqV8fc1kb9VinwShysQXPw7JB7hACGvcV1uYFn"
wormhole_governance = "wgvEiKVzX9yyEoh41jZAdC6JqGUTS4CFXbFGBV5TKdZ"
ntt_quoter = "9jFBLvMZZERVmeY4tbq5MejbXRE18paGEuoB6xVJZgGe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "keys/test.json"

[scripts]
test = "./scripts/run-ts-tests"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = true

[[test.genesis]]
address = "worm2ZoG2kUd4vFXhvjh93UUH596ayRfgQ2MgjNMTth"
program = "programs/example-native-token-transfers/tests/fixtures/mainnet_core_bridge.so"

[test.validator]
url = "https://api.mainnet-beta.solana.com"
ticks_per_slot = 16

[[test.validator.account]]
address = "2yVjuQwpsvdsrywzsJJVs9Ueh4zayyo5DYJbBNc3DDpn"
filename = "tests/accounts/mainnet/core_bridge_config.json"

[[test.validator.account]]
address = "9bFNrXNb2WTx8fMHXCheaZqkLZ3YCCaiqTftHxeintHy"
filename = "tests/accounts/mainnet/core_bridge_fee_collector.json"

[[test.validator.account]]
address = "DS7qfSAgYsonPpKoAjcGhX9VFjXdGkiHjEDkTidf8H2P"
filename = "tests/accounts/mainnet/guardian_set_0.json"
